name: Build and Release Grader Than Web Preview VSIX

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger workflow on version tag pushes (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Use Node.js version suitable for your project

      - name: Install dependencies
        run: npm install

      - name: Install VSCE (Visual Studio Code Extension Manager)
        run: npm install -g @vscode/vsce

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Package extension
        run: vsce package -o web-preview-${{ env.VERSION }}.vsix

      - name: Upload VSIX as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-preview-${{ env.VERSION }}.vsix
          path: ./web-preview-${{ env.VERSION }}.vsix

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download VSIX package
        uses: actions/download-artifact@v3
        with:
          name: web-preview-${{ env.VERSION }}.vsix

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: web-preview-${{ env.VERSION }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
